### ISSUE TITLE
Variable as a JSX parameter is broken

### ISSUE THREAD

**Issue by armed** [clavascript/cherry#53]
Cherry version: `0.0.0-alpha.54`

Two issues:
- argument is not wrapped with curly brackets, eg. `href={ url }`
- name of an argument does not contain an index `url` instead of `url1`

```clojure
(defn foo []
  (let [url "www.example.com"]
    #jsx [:a {:href url} "Go"]))
```
compiles to
```javascript
var foo = function () {
  let url1 = "www.example.com";
  {
    let x2 = <a href=url >{"Go"}</a>
    ;
    return x2;
  }
};

export { foo }
```

**Comment by borkdude** [comment]
Thanks! There's currently more broken, I think the jsx stuff needs to be deeper integrated into the compiler to support `if` etc but the above is fairly easy to fix I think.

**Comment by borkdude** [comment]
I investigated this issue and there is no quick hack to fix this. We need to support JSX as part of the compiler and not as a quick hack like I did before. I will look into this to better support JSX both in cherry and clavascript.

**Comment by borkdude** [comment]
Should work now
